trigger:
  - main

pool:
  name: Self

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

  - task: Maven@3
    inputs: 
      mavenPomFile: 'pom.xml'
      goals: 'package'
    displayName: 'Build with Maven'
