# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'  # Using a Microsoft-hosted agent with Ubuntu

variables:
  MAVEN_OPTS: '-Xmx1024m'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build and Test Job'
        steps:
          - task: UseMaven@4
            inputs:
              mavenVersionOption: 'Default'
              mavenPomFile: 'pom.xml'
              goals: 'clean install'
              options: '--batch-mode'

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/target/surefire-reports/*.xml'
              testResultsFormat: 'JUnit'
              failTaskOnFailedTests: true

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: 'Deploy Job'
        steps:
          - script: |
              echo "Deploying application..."
              # Add deployment steps here
            displayName: 'Deploy Script'

